name: Hub
main: com.javabean.hub.Hub
author: JavaBean
description: Allows admins to configure hub activities.
version: 1.0
api-version: 1.15
commands:
   hub:
      description: JavaBean Hub command.
      usage: /hub